import type { AdoptionRequestListItem } from "@/app/actions/admin-adoption-requests";

export const MOCK_ADOPTION_REQUESTS: AdoptionRequestListItem[] = [
  {
    id: "1",
    animal_id: "a1",
    name: "Maria Silva",
    email: "maria.silva@email.com",
    phone: "(48) 99999-1111",
    address: "Rua Exemplo, 100",
    city: "Florianópolis",
    message: "Tenho um quintal grande e já tive cachorros. Gostaria muito de dar um lar para o Thor.",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read: false,
    status: "pending",
    admin_comment: null,
    animal_name: "Thor",
    animal_type: "cachorro",
  },
  {
    id: "2",
    animal_id: "a2",
    name: "João Santos",
    email: "joao.s@email.com",
    phone: "(48) 98888-2222",
    address: "Av. Central, 200",
    city: "São José",
    message: null,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    status: "in_review",
    admin_comment: "Ligar na próxima semana para visita.",
    animal_name: "Luna",
    animal_type: "gato",
  },
  {
    id: "3",
    animal_id: "a3",
    name: "Ana Costa",
    email: "ana.costa@gmail.com",
    phone: "(48) 97777-3333",
    address: "Rua das Flores, 50",
    city: "Palhoça",
    message: "Moro em casa com jardim, sem outros pets. Busco um gato para companhia.",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    status: "responded",
    admin_comment: null,
    animal_name: "Mimi",
    animal_type: "gato",
  },
  {
    id: "4",
    animal_id: "a4",
    name: "Pedro Oliveira",
    email: "pedro.o@email.com",
    phone: "(48) 96666-4444",
    address: "Rua do Sol, 300",
    city: "Florianópolis",
    message: "Já adotei um cachorro da OBA antes. Quero dar oportunidade a outro.",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    status: "approved",
    admin_comment: "Documentação ok. Entrega combinada para sábado.",
    animal_name: "Rex",
    animal_type: "cachorro",
  },
  {
    id: "5",
    animal_id: "a5",
    name: "Carla Mendes",
    email: "carla.m@email.com",
    phone: "(48) 95555-5555",
    address: "Rua Pequena, 10",
    city: "Biguaçu",
    message: "Apartamento pequeno, mas posso dar muito amor.",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    status: "rejected",
    admin_comment: "Perfil não adequado para o animal no momento.",
    animal_name: "Bob",
    animal_type: "cachorro",
  },
];
