import type { AdoptionRequestListItem } from "@/components/admin/AdoptionRequestsList";

export const MOCK_ADOPTION_REQUESTS: AdoptionRequestListItem[] = [
  {
    id: "1",
    nome: "Maria Silva",
    email: "maria.silva@email.com",
    telefone: "(48) 99999-1111",
    cidade: "Florianópolis",
    mensagem: "Tenho um quintal grande e já tive cachorros. Gostaria muito de dar um lar para o Thor.",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read: false,
    status: "pending",
    admin_comment: null,
    animal_name: "Thor",
    animal_type: "cachorro",
  },
  {
    id: "2",
    nome: "João Santos",
    email: "joao.s@email.com",
    telefone: "(48) 98888-2222",
    cidade: "São José",
    mensagem: null,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    status: "in_review",
    admin_comment: "Ligar na próxima semana para visita.",
    animal_name: "Luna",
    animal_type: "gato",
  },
  {
    id: "3",
    nome: "Ana Costa",
    email: "ana.costa@gmail.com",
    telefone: "(48) 97777-3333",
    cidade: "Palhoça",
    mensagem: "Moro em casa com jardim, sem outros pets. Busco um gato para companhia.",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    status: "responded",
    admin_comment: null,
    animal_name: "Mimi",
    animal_type: "gato",
  },
  {
    id: "4",
    nome: "Pedro Oliveira",
    email: "pedro.o@email.com",
    telefone: "(48) 96666-4444",
    cidade: "Florianópolis",
    mensagem: "Já adotei um cachorro da OBA antes. Quero dar oportunidade a outro.",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    status: "approved",
    admin_comment: "Documentação ok. Entrega combinada para sábado.",
    animal_name: "Rex",
    animal_type: "cachorro",
  },
  {
    id: "5",
    nome: "Carla Mendes",
    email: "carla.m@email.com",
    telefone: "(48) 95555-5555",
    cidade: "Biguaçu",
    mensagem: "Apartamento pequeno, mas posso dar muito amor.",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
    status: "rejected",
    admin_comment: "Perfil não adequado para o animal no momento.",
    animal_name: "Bob",
    animal_type: "cachorro",
  },
];
